version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: pokemon_middleware:${POKEMON_MIDDLEWARE_VERSION:-latest}
    restart: always
    env_file:
    - .env
    environment:
      POKEMON_MIDDLEWARE_HOST: 0.0.0.0
